### ISSUE TITLE
Ability to stop simulator execution after initilizing demo data

### ISSUE THREAD

**Issue by anhaltFelix** [camunda-consulting/camunda-bpm-simulator#5]
I'd like to operate completly normal with my application after an initial generation of data but right now generation (and user task completition etc) continues even after initial start has finished.

**Comment by nevries** [comment]
The current behaviour is expected to work like that. So, this is a feature request for "turning off" all simulation actions.

**Comment by benhoffmann** [comment]
I think I already implemented something like this a while ago. You can call SimulationExecutor#stopSimulation().

But maybe I misunderstood your requirement - this will only stop an ongoing simulation and not "deactivate" the plugin altogether. I guess it depends on how you call the simulator when generating the demo data.

**Comment by nevries** [comment]
SimulationExecutor#stopSimulation stops a running "history simulation", but the plugin keeps active. In particular, all behaviour modifications the plugin did keep intact.

After some discussion we have to reword the demand: We want to disable the model modifications, so that we can deploy a process model without being simulated at all.
